transport.go

currently if I want to use a github preview api I need to set a specific `Accept` header but `RoundTrip` overrides whatever I set in my request with its own `Accept` header.  This change just adds on to existing `Accept` headers and doesn't override them.

RoundTrip: don't override any existing `Accept` header, add on to it

---

appsTransport.go
appsTransport_test.go
transport.go

Splits authentication as a GitHub App into an `AppsTransport` which implements `http.RoundTripper`. Note this is a WIP, and requires documentation and closer review for cleanup.
For review by @itay.
Resolves #6.

Split authentication as an app into AppsTransport

---

transport.go
transport_test.go

/installations/:installation_id/access_tokens is deprecated for
/apps/installations/:installation_id/access_tokens.
See
https://developer.github.com/changes/2018-08-16-renaming-and-deprecation-of-github-app-installation-access-token-route/
for more details.

Update GitHub App Installation Access Token Route

---

appsTransport.go
appsTransport_test.go

Certain Apps endpoints require a different Accept header for early
access.

AppsTransport: Do not override Accept headers.

---

README.md
appsTransport.go
appsTransport_test.go
transport.go
transport_test.go

GitHub App documentation uses the the term `app ID` in its docs. This
changes all references to be consistent with this. See
https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app
for an example.

Change Integration ID -> App ID to match GitHub documentation.

---

appsTransport.go
transport.go

This change makes ghinstallation consistent with
`github.com/google/go-github` for App and Installation identifiers. See
https://github.com/google/go-github/issues/597 for related discussion.
Fixes #27

BREAKING CHANGE: Change IDs from int -> int64.

---

go.sum
transport.go

When we create `Transport` using an existing `AppsTransport`, using `NewFromAppsTransport` function. It extracts the necessary  feileds (e.g., `appID` and `tr` ) from `AppsTransport`.
**The issue**: if the BaseURL on `AppsTransport` has been changed (e.g., point to an enterprise server), the `NewFromAppsTransport` function uses the default `apiBaseURL` which is the public Github API.
**Solution**: read the BaseURL from `AppsTransport`.

Fix API BaseURL when use NewFromAppsTransport

---

transport.go

If a GitHub App is suspended, the refreshToken() roundtrip will return a 403 HTTP Status Code.
In the error message, this is not visible.
This PR is doing a small quick fix to add the Status code into the error message
A better solution would be to include the full response for inspection into the error.
For this, we would need a custom error type.
@bradleyfalzon @wlynch Would you be open to such a PR?

Add StatusCode to error message if refreshToken() fails due to an suspended app

---

appsTransport.go

The package is not compiling. The package `dgrijalva/jwt-go` got updated to v4. However, the new version changes the type for the claim's time form `int64` to `jwt.Time`.
```
% go test
./appsTransport.go:68:3: cannot use time.Now().Unix() (type int64) as type *jwt.Time in field value
./appsTransport.go:69:3: cannot use time.Now().Add(time.Minute).Unix() (type int64) as type *jwt.Time in field value
FAIL    github.com/bradleyfalzon/ghinstallation [build failed]
```
Such bug could be caught by running the tests. I suggest utilizing the Github Actions to build and run the tests on each commit. I can submit a pull request to setup the Github Actions if you agree to do so.

Fix a breakage change in the jwt-go v4 update

---

transport.go

**What type of PR is this?**
feature
**What this PR does / why we need it**:
If the refreshToken operation fails (e.g., the GitHub app has been suspended), the RoundTrip is returning an error. However, the caller is not able to figure out the root cause of the failure.
This commit introduces a custom error that contains the original request and response for further inspection.
**Special notes for your reviewer**:
This PR was mentioned shortly in https://github.com/bradleyfalzon/ghinstallation/pull/44 with @wlynch 
**Does this PR introduce a user-facing change?**:
None
**Additional documentation e.g., usage docs, etc.**:
None

Introduce a custom error for refreshToken operation

---

go.mod
go.sum
transport.go
transport_test.go

v35.1.0 (and the versions until v30) contains a lot of bugfixes and additional fields for structs like `Repositories`

Upgrade go-github from v30.0.0 to v35.1.0

---

transport.go

The header `application/vnd.github.machine-man-preview+json` graduated in August 2020.
See https://developer.github.com/changes/2020-08-20-graduate-machine-man-and-sailor-v-previews/
According to the API docs [Create an installation access token for an app](https://docs.github.com/en/rest/reference/apps#create-an-installation-access-token-for-an-app), the header `application/vnd.github.v3+json` is suggested.

Replace "machine-man-preview" header with "application/vnd.github.v3+json"

---

appsTransport.go
appsTransport_test.go

GitHub is rejecting JWTs whose expiry timestamps
have fractional seconds with the error:
Expiration time' claim ('exp') must be a numeric value representing
the future time at which the assertion expires
Whereas jwt-go supports fractional seconds, and therefore serializes
timestamps truncated to microsecond resolution.
This change truncates the timestamps before passing to jwt-go
which fixes the issue.

Truncate issue and expiry times to whole seconds

---

go.mod
go.sum
transport.go
transport_test.go

Similar in scope to #49, update the backing version of go-github to pick up some fixes.

Update go-github to v0.38.0

---

README.md
go.mod

Resolves #50. When this repo cut a v2 release, it accidentally "broke" the conventions for go modules in v2.
I think this is all that is necessary to fix the issue.
See https://blog.golang.org/v2-go-modules for more details.

Bump module version to v2

---

go.mod
go.sum
transport.go
transport_test.go

Updates the version of go-github to latest v40 that was recently released. https://github.com/google/go-github/releases/tag/v40.0.0

Update go-github to v40

---

transport.go
transport_test.go

When using a custom Github URL (e.g. for a Github Enterprise instance)
one might specify it with a trailing slash. This can lead to URLs
containing two successive slashes.
Github will not ignore this, but instead return a HTTP 401 Forbidden
response. It might be nice to address the issue by removing trailing
slashes when joining with a string that has a leading slash.

trim trailing slashes from base url

---

transport.go
transport_test.go

Fixes #20 
Without this, it's impossible to use [`httpcache`](https://github.com/gregjones/httpcache) together with this package, as `httpcache` expects the parent RoundTripper to respect the [RoundTripper contract](https://pkg.go.dev/net/http#RoundTripper):
```
// RoundTrip should not modify the request, except for
// consuming and closing the Request's Body. RoundTrip may
// read fields of the request in a separate goroutine. 
```
ghinstallation currently does not comply with the contract, as it modifies the request headers (in addition to not closing the body in case of errors).
As a result of this, no request will ever result in a hit in the cache because ghinstallation modifies some of the request headers that the Github API includes in the Vary response header (Accept, …

Respect the http.RoundTripper contract

---

transport.go
transport_test.go

This change prevents the Accept header `application/vnd.github.v3+json` from being added to the headers in case there is already an Accept header.
The mentioned header is necessary for most interactions with the GitHub API, but it also influence the behaviour of some resource call in an unexpected way.
Example:
When downloading a release with the [go-github](https://github.com/google/go-github) library, an Accept header `application/octet-stream` is added by the latter, then ghinstallation adds the Accept header `application/vnd.github.v3+json`.
The response to such request isn't the content of the release, as one could expect when using the function `DownloadReleaseAsset` but a json describing the release.
This PR prevents this behaviour from happening and tackle the issue #12

Prevent adding Accept header when already one.

---

transport.go
transport_test.go

Since it could be interesting in some cases, return this for the user to examine.
Also factor out the "is a token expired" logic and return the current value of "we think it's expired" when calling Expiry().
expiresAt, expired, err := trans.Expiry()

Add Transport.Expiry() to query token expiration

---

README.md
appsTransport.go
appsTransport_test.go
sign.go

This change creates a new `Signer` interface which encapsulates jwt.SigningMethod + the key material use to sign JWT tokens.
This allows clients to modify how JWT tokens are signed by passing in their own Signer. In particular, I'm interested in coupling this with something like
https://github.com/golang-jwt/jwt#extensions to allow for JWT signing backed by KMS systems (Vault, Cloud KMS, etc) where the private key never resides on the local client.
Introduces a new `AppsTransportOptions` to make it easier to make new transport creation options without needing to make new funcs each time. For now only added `WithSigner`, but we could easily extend this out to other config options (Client, BaseURL, etc.)
Finally, upgrades deprecated `jwt.StandardClaims` -> `jwt.RegisteredClaims`.

Allow JWT signing method to be configurable.

---

transport.go
transport_test.go

Hey @bradleyfalzon!
Thanks for creating https://github.com/bradleyfalzon/ghinstallation!
An issue we've been having is that, when using a custom http client underneath ghinstallation and returning special error types from it, ghinstallation wraps them in HTTPError which we can't unwrap using errors.As.
Would you consider accepting this fix upstream?

HTTPError should be unwrappable.

---

appsTransport.go
appsTransport_test.go
transport.go
transport_test.go

Without this, it is not possible to know which app or installation a given transport is for without tracking it separately.
These are getter functions that return copies so they are backwards compatible and cannot cause any issues or break a transport.

feat: add ID getter methods

---

README.md

Also update godoc link to v2 module.

Add note about `New()` to README.md example.

---

.github/dependabot.yml
.github/workflows/go.yml
go.mod

- update go mod to go1.21
- update ci actions and test with supported go versions
- add dependabot config for github actions

Updates go.mod / ci / dependabot config

---

go.mod
go.sum

Bumping jwt dependency due to newly found CVE https://github.com/advisories/GHSA-29wx-vh33-7x7r
Go version bumped due to github.com/google/go-github/v66 requirement

Bumped github.com/golang-jwt/jwt/v4 due to security CVE-2024-51744

---

.github/workflows/go.yml

cc @wlynch 
note: we should consider to bump min go to 1.22 and drop go1.21

test/build with go1.23

---

.github/workflows/go.yml

- remove go1.21 as only latest two go release lines are maintained by go team
- test out go1.24rc1

chore: add `go1.24-rc1` for matrix check

---

go.mod
go.sum
transport.go
transport_test.go

Update to https://github.com/google/go-github/releases/tag/v72.0.0

Update to go-github v72

---

README.md

This PR updates README:
- `GO111MODULE=on` is no longer required for modern go versions
- replace GoDoc badge with Go Reference badge
- improve heading formatting
- replace whitespaces with tabs in Go examples
- update GitHub doc link

Update README: improve formatting, replace GoDoc with GoReference

---

go.mod
go.sum
transport.go
transport_test.go

Now that https://github.com/google/go-github/releases/tag/v75.0.0 is out

Update google/go-github to v75
